# Generated by Django 4.1.2 on 2022-10-15 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a GPU name', max_length=40)),
                ('performance', models.IntegerField()),
                ('vram', models.IntegerField()),
                ('powerSupply', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Psu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a PSU name', max_length=40)),
                ('power', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RamSlotType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a ram slot type (e.g. DDR1)', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SocketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a socket type (e.g. LGA 1700)', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='StorageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a storage type (e.g. SDD)', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Storage name', max_length=40)),
                ('capacity', models.IntegerField()),
                ('storageType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.storagetype')),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a RAM name', max_length=40)),
                ('size', models.IntegerField()),
                ('ramSlotType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.ramslottype')),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Motherboard name', max_length=40)),
                ('m2', models.IntegerField()),
                ('slotsRam', models.IntegerField()),
                ('ramSlotType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.ramslottype')),
                ('socket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.sockettype')),
            ],
        ),
        migrations.CreateModel(
            name='CpuCooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a CPU cooler name', max_length=40)),
                ('tdp', models.IntegerField()),
                ('socket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.sockettype')),
            ],
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a CPU name (e.g. intel core i5)', max_length=40)),
                ('cores', models.IntegerField()),
                ('threads', models.IntegerField()),
                ('performance', models.IntegerField()),
                ('tdp', models.IntegerField()),
                ('socket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.sockettype')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a socket type (e.g. Vasyas computer)', max_length=200)),
                ('cpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.cpu')),
                ('cpuCooler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.cpucooler')),
                ('gpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.gpu')),
                ('motherboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.motherboard')),
                ('psu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.psu')),
                ('ram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.ram')),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.storage')),
            ],
        ),
    ]
